### ISSUE TITLE
Followed Guide, End Result After Launchung a Game

### ISSUE THREAD

**Issue by SykkNyzz** [leomaurodesenv/cemu-linux#4]
002d:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000092FD80
002c:fixme:wbemprox:client_security_SetBlanket 000000006775DD00, 0000000000683600, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
002c:fixme:wbemprox:client_security_Release 000000006775DD00
002c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0030:fixme:msg:ChangeWindowMessageFilter c055 00000001
0030:fixme:msg:ChangeWindowMessageFilter 111 00000001
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
0030:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 6.0, 128 bits)").
0037:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpWithDataSegs
0037:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpWithHandleData

**Comment by leomaurodesenv** [comment]
What that means? Which command result this message?

**Comment by leomaurodesenv** [comment]
Closed by no reply
