### ISSUE TITLE
GamePad view is black

### ISSUE THREAD

**Issue by EmmmaTech** [leomaurodesenv/cemu-linux#6]
Hello, so I just recently tried this tutorial out to play Super Mario 3D World on my laptop. It works really well, but there is an issue. For some reason, the GamePad screen isn't displaying anything. Any ideas?

**Comment by leomaurodesenv** [comment]
Hello @EmreTech , 
I'm in hear that you are trying this tutorial! 
Can you show us an image of you screen? Also copy & paste the terminal output.

**Comment by EmmmaTech** [comment]
Sure! I'll copy the Terminal output and what the GamePad screen looks like as soon as I can

**Comment by leomaurodesenv** [comment]
Closed by no reply

**Comment by EmmmaTech** [comment]
I was going to close this anyways
Forgot to do it lol
